export default function Head() {
  return (
    <>
      <title>NFT Pod - On-demand NFT prints /w ownership verification via QR-Code</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/fav.png" />
    </>
  )
}
